### ISSUE TITLE
Update test suite

### ISSUE THREAD

**Issue by swkeemink** [rochefort-lab/fissa#10]
The test suite is now significantly out-of-date with the actual FISSA functions. This should be updated.

**Comment by scottclowe** [comment]
There have been updates to the test suite since, particularly in PRs #35 and #62. Further tests are added in #54.

Some of these tests are very solid, in particular since creating and adding the test resources https://github.com/rochefort-lab/fissa/tree/master/fissa/tests/resources/a.

However, some of my tests are still rather lose, and could do with more work. In particular, the matlab file generation test only check whether the code executes and doesn't inspect the output. The neuropil tests also only check the code executes and the output has the right shape, without checking its exact contents.
