### ISSUE TITLE
Change the number of iterations and trials 

### ISSUE THREAD

**Issue by foustoukosg** [rochefort-lab/fissa#149]
Hello again,

Sorry to bother you again.

I have a short question that might have a quick answer.
Do you know if there is a easy way to change the number of iterations and number of trials for each roi until it reaches convergence?

It's rare but it happens on my data that I cant reach convergence.

Thanks a lot in advance,
Georgios

**Comment by swkeemink** [comment]
This is not currently an option, but should be there and is fairly easy to implement.

You can edit ```maxiter``` and ```maxtries``` in these lines https://github.com/rochefort-lab/fissa/blob/2077a8c8a029948dcf1d4c352f785700f42aff9f/fissa/core.py#L118-L120 
If you want to edit FISSA code, instead of the standard pip install it's best to install the source code as follows:
git clone (or manually download) the FISSA code:
```git clone git@github.com:rochefort-lab/fissa.git```
Then in your terminal move to the FISSA source folder ant type
```pip install -e .```
which will globally install the FISSA package based on this local folder. Then you can make any changes to the code you want.

To close this issue, we will also eventually add these as an input option, but for now you could quickly do it like this.

**Comment by swkeemink** [comment]
@scottclowe I'm going to do a PR for this too. I'm thinking of doing a  kwargs rather than a few new parameters. In particular 
maxiter, tol, and maxtries.
For completeness we should also add alpha and perhaps alpha to that but that would change how that would previously have been done.
Could also just add maxiter, tol, and maxtries as extra inputs as we have been doing so far.

**Comment by scottclowe** [comment]
Yes, the arguments which are available in the inner functions should be added to the API. They should be added as regular parameters though, not by catching any arbitrary arguments given with **kwargs. That would lead to silent errors when users misspell arguments.

We should finish refactoring core before adding these arguments.

**Comment by scottclowe** [comment]
When you're adding the new parameters, please indicate the version in which they are added with the `versionadded` directive, like so:

```
    Parameters
    ----------
    x : array_like
        Input array or object that can be converted to an array.
    niter : None or int, optional
        Description here.

        .. versionadded:: 1.0.0

    other_arg : None or float, optional
        Lorem ipsum
```

You can see this in effect with a new function for [numpy.broadcast_shapes](https://numpy.org/doc/stable/reference/generated/numpy.broadcast_shapes.html?#numpy.broadcast_shapes) corresponding [source](https://github.com/numpy/numpy/blob/v1.20.0/numpy/lib/stride_tricks.py#L438), and for a new parameter of an existing function with the `axis` argument of [numpy.all](https://numpy.org/doc/stable/reference/generated/numpy.all.html?#numpy.all) corresponding [source](https://github.com/numpy/numpy/blob/v1.20.0/numpy/core/fromnumeric.py#L2364-L2373).
