### ISSUE TITLE
Make a datahandler class

### ISSUE THREAD

**Issue by swkeemink** [rochefort-lab/fissa#16]
Currently the datahandler functions come from a script. If one wants to use a home-made datahandler, one has to make their own version of the script and import it. 

A much cleaner way to do this would be make the datahandler a class, which can be inhereted, after which the relevant aspects of it can be changed. This can then be passed to the existing Experiment class as it is done for imported scripts at the moment.

**Comment by swkeemink** [comment]
This is now done in https://github.com/rochefort-lab/fissa/pull/156.

**Comment by scottclowe** [comment]
It's better practice to leave the issue open until the PR is merged, since the issue persists in the codebase until the PR is done. You can get this to happen automatically by including the text "Closes #16" (etc) in the content of the PR which closes the issue, and then GitHub will automatically close the linked issue when the PR is merged.
