### ISSUE TITLE
Source separation

### ISSUE THREAD

**Issue by ehennestad** [rochefort-lab/fissa#23]
I am trying to implement your method in Matlab, and I have a few questions. But first I would like to thank you for making incredible well organized and easy to read python code!

In the documentation of neuropil.separation the description of the input S is given:

S : array_like
        2d array with signals. S[i,j], j = each signal, i = signal content.
        j = 0 is considered the primary signal. (i.e. the somatic signal)

I understood it that the signals/timeseries of each roi is along the first dimension, and the different rois along the second dimension, so that the array is of size nSamples x nRois. However, both the output of the signal extraction method and the treatment of S within the separation function seems to me to have to opposite dimension order.

Also, I am wondering about the normalization of A_sep, the separation coefficient matrix. I understood from the paper and the method description that normalizing the scores would ensure that the signals are always positive. However, when the signals are matched, the original score matrix is used, not the normalized one. 

Last, when I run nnmf in Matlab with the same number of components as number of rois ( I use the default values, so there are 5 components in total), I always get a score matrix where one element is 1 and the rest are zero for each roi signal. If I set the components to 4 instead, the score matrix looks more like expected, but the resulting demixed signal for the original roi sometimes looks good and sometimes not. The MATLAB implementation of nnmf seems to be a bit different than the scikit one, for example I can not set the parameter alpha (sparseness parameter). I have no experience with the nnmf method and if you have any ideas, or any knowledge of the matlab implementation, I would be very grateful.

**Comment by swkeemink** [comment]
Hi there! Thanks for your interest in our method, and apologies for the late reply.

Re: dimension order of S. Across FISSA, we use the convention that the first dimension is the subregion number, and the second dimension is time. However, in sklearn this is the other way around, which is why you see it  use the opposite dimension order in neuropil.separate sometimes.

Re: normalization of A_sep. The non-negativity is enforced by the nmf method itself. The normalization of A_sep is only done to estimate how strong each signal is present in each subregion, and which should be taken as the somatic signal, by ordering them accordingly:
https://github.com/rochefort-lab/fissa/blob/16347caf141259b63ccacc007d21c856966b5b2f/fissa/neuropil.py#L180-L193 
As the normalized A_sep matrix does not represent the actual weight of each signal anymore, the weights from the NON-normalized A_sep are used to scale the different signals appropriately for the central ROI:
https://github.com/rochefort-lab/fissa/blob/16347caf141259b63ccacc007d21c856966b5b2f/fissa/neuropil.py#L195-L198

Re: Matlab implementation. The standard Matlab nmf does not perform anywhere as well as Python's sklearn implementation, in my experience. A possible candidate (with a sparse method) can be found here: https://sites.google.com/site/nmftool/, but better ones might exist, as I haven't looked into it in a while. If there is no sparsity constraint, and the initialization of the mixing matrix is set as an identity matrix, a trivial solution to the nmf problem is to just keep the unity matrix and each original signal, which is possibly what is going on for you with 5 input and 5 output signals.

**Comment by ehennestad** [comment]
> Re: dimension order of S. Across FISSA, we use the convention that the first dimension is the subregion number, and the second dimension is time. However, in sklearn this is the other way around, which is why you see it use the opposite dimension order in neuropil.separate sometimes.

`Parameters
    ----------
    S : array_like
        2d array with signals. S[i,j], j = each signal, i = signal content.
        j = 0 is considered the primary signal. (i.e. the somatic signal)`

I think this is a bit confusing then, does it not suggest that time is along the first dimension and that the second dimension is the subregion number?

> Re: normalization of A_sep. The non-negativity is enforced by the nmf method itself. The normalization of A_sep is only done to estimate how strong each signal is present in each subregion, and which should be taken as the somatic signal, by ordering them accordingly:

Ah, Now I see. It is normalized along columns, but then you sort along rows.

> Re: Matlab implementation. 

Thanks for the explanation. Now I have tried some different MATLAB implementations, but as I did not quite figure out which parameters correspond with those described in your paper/method, I just call your separate function from MATLAB. It works very nicely, its impressive. 

I made one observation, which gave me an idea. I observe in some of my ROIs that there is a dendrite within the ROI boundary. It is much smaller than the area of the ROI, but whenever it is mostly within the ROI boundary, this method can not separate it. I guess it would be trivial to split the ROI into subregions and do the same signal separation and remove parts that belong to smaller source.
