### ISSUE TITLE
Invalid cutoff frequency in calc_deltaf

### ISSUE THREAD

**Issue by swkeemink** [rochefort-lab/fissa#25]
Also I am seeing an error when I try and call calc_deltaf which states the below:

Traceback (most recent call last):
  File "C:\PostDoc Docs\code\python\fissa\examples\basic_usage_v2.py", line 27, in <module>
    experiment.calc_deltaf(freq = 1.3)
  File "C:\ProgramData\Anaconda2\lib\site-packages\fissa\core.py", line 442, in calc_deltaf
    raw_f0 = deltaf.findBaselineF0(raw_conc, freq)
  File "C:\ProgramData\Anaconda2\lib\site-packages\fissa\deltaf.py", line 57, in findBaselineF0
    b = scipy.signal.firwin(nfilt, cutoff=fw_base / nyq_rate, window='hamming')
  File "C:\ProgramData\Anaconda2\lib\site-packages\scipy\signal\fir_filter_design.py", line 394, in firwin
    raise ValueError("Invalid cutoff frequency: frequencies must be "
ValueError: Invalid cutoff frequency: frequencies must be greater than 0 and less than fs/2.

I am guessing my sampling freq (1.3Hz) is too low?

_Originally posted by @GrimmSnark in https://github.com/rochefort-lab/fissa/issues/24#issuecomment-426016204_

**Comment by scottclowe** [comment]
Hi @GrimmSnark,

Yes, you are right. This problem is occurring because your sampling frequency is lower than the Δf/f0 calculation is expecting.

To find the baseline, we first smooth the signal to remove high frequency noise, and use a frequency of 1Hz to do so. Of course, with frequencies lower than 1Hz, it is not necessary to smooth the signal. I will fix our methodology so it does not try to smooth the data when the input has a sampling frequency lower than 1Hz, and for sampling frequencies in the 1Hz to 2Hz range (such as your own data), smooth it at  the Nyquist frequency of half the sampling rate.

While you are waiting for this fix to deployed, I recommend you do one of the following:
- Work with the raw signal instead of Δf/f0.
- Lie to the function and tell it your data is sampled at 2Hz.

I believe if you lie to the function about your sampling rate,

    experiment.calc_deltaf(freq = 1.3)

this will provide the same solution as I am about to implement. The data will actually be smoothed at 0.65Hz instead of 1Hz.

**Comment by GrimmSnark** [comment]
Thank you very much for your quick solution. I will give the work around a go in the meantime.
