### ISSUE TITLE
Fissa starts region growing and data extraction without experiment.separate()

### ISSUE THREAD

**Issue by YoshiLucas** [rochefort-lab/fissa#81]
When I was playing around with FISSA a few weeks ago, it wouldn't do anything after I set up the experiment, until I typed in experiment.separate() into the console. However, when I tested it out today, it would start region growing and data extraction, almost always failing to finish even after running it for a few minutes.

**What I did:**

I ran the following code on a Python (3.7.6, 64-bit) IDE (Spyder 4.0.1) on Windows 10 (1909, latest updates installed) using FISSA (0.6.1):

import fissa

rois_location = # ROI zip on local hard drive, taken from FISSA example folder
images_location = # Images on local hard drive, taken from FISSA example folder
output_folder = # Folder on local hard drive

experiment = fissa.Experiment(images_location,rois_location,output_folder,ncores_preparation=4,ncores_separation=4)

**What I expected**

I expected the code to set up the class 'experiment' as it had always done a few weeks ago.

**What happened**

Despite not having typed 'experiment.separate()', FISSA would start the region growing and data extraction all by itself, while getting stuck at signal separation.

**Update**

As I was originally filing out this issue, I was playing around with FISSA and discovered that the above was caused by the presence of 'preparation.npy' and 'separated.npy' in the output folder. When I deleted those, FISSA wouldn't start region growing and data extraction without me typing experiment.separate(). I'm not sure if it's supposed to do that, but I thought I should file an issue report.

Something even weirder is that when the code is run on Spyder (with the output folder emptied), 9 times out of 10 it gets stuck on the 'Doing signal separation' step. However, whenever I tested this out on the python console that I booted directly from the Anaconda powershell prompt, it would finish within a few seconds. It still has the bug (?) where it starts region growing and data extraction by itself, though, but in the dozen or so times that I've run the code, it's given me an output without getting stuck like Spyder.

I've restarted my PC, I've uninstalled FISSA and reinstalled it, but it doesn't seem to fix the issue of FISSA not running properly on Spyder. I'm not sure if this was a problem with Spyder or with FISSA, but I wanted to post this issue because of the signal separation running by itself, in case it was a bug. This was my first issue posting I've done on GitHub so hopefully I followed the guidelines correctly. If I could help getting this to work, it would be a tremendous help to the lab I'm working for. Thank you in advance!

**Comment by scottclowe** [comment]
Hi Yoshi, thanks for letting us know about this issue. I appreciate you including plenty of details, which makes it much easier to work out what is going wrong.

You are correct that FISSA shouldn't start processing the data when you create a new experiment object with `experiment = fissa.Experiment()`, it should wait until you run `experiment.separate()`.

The reason why it is starting to process the data immediately is because FISSA is supposed to load up previously generated data when it is initialised (see [this line](
https://github.com/rochefort-lab/fissa/blob/fb239b20956625f709e516370a3ffd08a9770489/fissa/core.py#L240)), and the way that it detects that is by the presence of `preparation.npy` or `separated.npy` files in its output directory. If those files are already there, it tries to load them.
But if it tries to load in existing data and fails, it does the processing again and overwrites the file (see [lines here](https://github.com/rochefort-lab/fissa/blob/fb239b20956625f709e516370a3ffd08a9770489/fissa/core.py#L282-L286)).

I believe the problem is that when you run the code in Spyder, the code runs correctly until it comes time to save the data, at which point there is a problem and the save file is only partially created, resulting in a corrupted file which cannot be loaded. We are using [`numpy.save`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html) to save the data, so I guess there is a problem with using this from Spyder.

You say Spyder "gets stuck on the 'Doing signal separation' step". **Is there an error message?** Or does it run forever, until you kill the process?

**Do you know what version of numpy Spyder is using, and what version Anaconda is using?** I suspect they may be different. You can check by running `import numpy; print(numpy.__version__)` (within python) at each shell prompt.

At some point, I'll look into changing the code so it doesn't automatically reprocess corrupted data until `experiment.separate()` is called.
But I think the more pressing issue for you is being able to run the separation step and save the result correctly, since that will also resolve your problem with the `separate` step starting automatically.

**Comment by YoshiLucas** [comment]
Dr. Lowe,

Thank you for responding.

I agree with you that FISSA most likely gets stuck in a loop when trying to save, as it did create `preparation.npy` but not `separated.npy` when it gets stuck. And by stuck, I mean that the message 'Doing signal separation....' shows up, and the CPU usage remains quite high indefinitely until I kill off the console. Interestingly, even a keyboard interrupt cannot seem to stop the console once it gets stuck in this loop, as I'm forced to exit out of Spyder to kill it off.

Spyder seems to be able to save the data correctly once out of every dozen or so tries, but I've failed to determine what conditions seem to cause this error, as it seems random. The Anaconda version, on the other hand, hasn't failed yet over the dozen times that I've tested it.

Another interesting thing I've noticed is that when it does work on Spyder, it doesn't show the 'NMF converged after n iterations' message, while the Anaconda console displays it.

Since Spyder and Anaconda should be using the same environment, the existence of this bug itself is puzzling. I've checked with both consoles and they seem to be using numpy 1.18.1. I believe I may have updated numpy between when FISSA was working fine a few weeks ago and now, when FISSA stopped working on Spyder. Should I try reverting numpy to an older but compatible version to see if it would solve the issue?

**Comment by scottclowe** [comment]
Hi @YoshiLucas,

Apologies for the delayed response. It turned out that this problem was caused by a combination of three things:

1. In version 1.16 of numpy, [numpy.load](https://numpy.org/doc/stable/reference/generated/numpy.load.html)'s default behaviour changed to `allow_pickle=False` instead of `allow_pickle=True`. If you read the documentation for numpy.load, you'll see that this was done to prevent a security hole with loading from pickles. However, numpy did not change the default behaviour of [numpy.save](https://numpy.org/doc/stable/reference/generated/numpy.save.html), which remains to save with `allow_pickle=True`. FISSA was saving its cache files with the default setting of numpy.save, and loading them with the default setting of numpy.load, which became problematic once version 1.16 was released, and caused an error every time FISSA tried to load a cache file.

2. As described above, when a new `fissa.Experiment` instance is created, it checks to see if a cache file already exists and if it does it loads it into memory. Consequently, combined with (1), if a pickled cache file already existed fissa was immediately trying to load it and raising an error when it failed to do so.

3. We were using an old formulation for multiprocessing which runs with Python 2.7, instead of a more modern approach with a context wrapper as would be standard for Python 3. On Python 3.8 (and possibly other versions of Python 3 as well, as you report this was on Python 3.7), the code would lock up entirely if there was an error thrown in one of multiprocessing threads.

Issues (1) and (3) have now been addressed, so if you upgrade to the latest version of FISSA (version 0.7.0), that should entirely resolve your problems. Let us know if the issue persists or you have other problems. We'll work on something soon which also adds the option to not use the cache file, but as I say your current problem should be resolved with v0.7.0 and above.

Thanks again for reporting the issue you were having and providing us with a good deal of detail about the problem you were experiencing, it is much appreciated!
